#pragma once

typedef enum {
    COMMAND_NONE = 0,

    // --- Editing ---
    COMMAND_CUT,
    COMMAND_COPY,
    COMMAND_PASTE,
    COMMAND_DELETE,
    COMMAND_DELETE_FORWARD,
    COMMAND_SELECT_ALL,
    COMMAND_UNDO,
    COMMAND_REDO,
    COMMAND_INSERT_TAB,
    COMMAND_EDITOR_KEYDOWN,
    COMMAND_EDITOR_TEXT_INPUT,

    // --- File / Save ---
    COMMAND_SAVE_FILE,
    COMMAND_SAVE_ALL,
    COMMAND_RENAME_FILE,
    COMMAND_CONFIRM_RENAME,
    COMMAND_CANCEL_RENAME,
    COMMAND_NEW_FILE,
    COMMAND_NEW_FOLDER,
    COMMAND_DELETE_ENTRY,    
    COMMAND_DELETE_FILE,
   COMMAND_DELETE_FOLDER,
    COMMAND_OPEN_FILE,
    COMMAND_CLOSE_FILE,
    COMMAND_CHOOSE_WORKSPACE,
    COMMAND_RELOAD_WORKSPACE,

    // --- Navigation ---
    COMMAND_GO_TO_LINE,
    COMMAND_INSERT_NEWLINE,
    COMMAND_FOCUS_EDITOR,
    COMMAND_FOCUS_TERMINAL,
    COMMAND_FOCUS_TOOL_PANEL,
    COMMAND_FOCUS_CONTROL_PANEL,
    COMMAND_FOCUS_ICON_BAR,
    COMMAND_FOCUS_MENU_BAR,
    COMMAND_TOGGLE_SIDEBAR,

    // --- Build / Run ---
    COMMAND_BUILD_PROJECT,
    COMMAND_RUN_EXECUTABLE,
    COMMAND_DEBUG_EXECUTABLE,
    COMMAND_STOP_BUILD,
    COMMAND_OPEN_BUILD_LOG,

    // --- Misc / Global ---
    COMMAND_TOGGLE_FULLSCREEN,
    COMMAND_SHOW_COMMAND_PALETTE,
    COMMAND_TRIGGER_SEARCH,
    COMMAND_TRIGGER_REPLACE,
    COMMAND_EXECUTE_MACRO,
    COMMAND_SHOW_SETTINGS,

    // --- Terminal Commands ---
    COMMAND_CLEAR_TERMINAL,

    // --- Editor Tab / Split ---
    COMMAND_SWITCH_TAB,
    COMMAND_CLOSE_TAB,
    COMMAND_SPLIT_VIEW_VERTICAL,
    COMMAND_SPLIT_VIEW_HORIZONTAL,
    COMMAND_CLOSE_SPLIT,

    // --- Panel Toggles ---
    COMMAND_TOGGLE_CONTROL_PANEL,
    COMMAND_TOGGLE_TOOL_PANEL,
    COMMAND_TOGGLE_TERMINAL_PANEL,


    // --- Control Panel Specific
    COMMAND_TOGGLE_LIVE_PARSE,
    COMMAND_TOGGLE_SHOW_ERRORS,
    COMMAND_TOGGLE_SHOW_MACROS,

    // --- Task Panel Specific ---
    COMMAND_DELETE_TASK,
    COMMAND_RENAME_TASK,
    COMMAND_ADD_TASK,
    COMMAND_MOVE_TASK_UP,
    COMMAND_MOVE_TASK_DOWN,
    COMMAND_TOGGLE_TASK_STATE,
    COMMAND_TOGGLE_TASK_EXPANDED,

    // --- Git Panel Specific ---
    COMMAND_REFRESH_GIT_STATUS,
    COMMAND_STAGE_SELECTED_FILE,
    COMMAND_COMMIT_CHANGES,
    COMMAND_REFRESH_LIBRARY,
    COMMAND_CLEAR_ANALYSIS_CACHE,

    // --- Error Panel Specific ---
    COMMAND_JUMP_TO_FIRST_ERROR,
    COMMAND_CLEAR_ERROR_LIST,

    // --- Asset Panel Specific ---
    COMMAND_REFRESH_ASSET_LIST,
    COMMAND_PREVIEW_SELECTED_ASSET,

    // --- Build Output Panel Specific ---
    COMMAND_CLEAR_BUILD_OUTPUT,
    COMMAND_SCROLL_BUILD_OUTPUT_TOP,


    // --- Popup Specific ---
    COMMAND_DISMISS_POPUP,

    // --- Icon Bar Commands ---
    COMMAND_SELECT_ICON_PROJECT_FILES,
    COMMAND_SELECT_ICON_LIBRARIES,
    COMMAND_SELECT_ICON_BUILD_OUTPUT,
    COMMAND_SELECT_ICON_ERRORS,
    COMMAND_SELECT_ICON_ASSET_MANAGER,
    COMMAND_SELECT_ICON_TASKS,
    COMMAND_SELECT_ICON_VERSION_CONTROL

} InputCommand;
