#ifndef IDE_UI_PANEL_METRICS_H
#define IDE_UI_PANEL_METRICS_H

#define IDE_UI_DENSE_ROW_HEIGHT 14
#define IDE_UI_DENSE_HEADER_HEIGHT 14
#define IDE_UI_TREE_INDENT_WIDTH 10

#endif // IDE_UI_PANEL_METRICS_H
