BASE_CFLAGS = -Wall -std=c99 -MMD -MP $(INC_DIRS) -I$(FISICS_INC) -I$(FISICS_LEXER_INC) $(LLVM_CFLAGS) -DVK_RENDERER_SHADER_ROOT=\"$(ABS_VK_SHADER_ROOT)\" $(TIMER_HUD_INC)
BASE_LDFLAGS = $(LIB_DIRS) -lSDL2 -lSDL2_ttf -lSDL2_image -ljson-c $(VULKAN_LIBS) $(SDL_MIXER_FLAGS) $(FISICS_LIB) $(LLVM_LDFLAGS) $(LLVM_LIBS)

ifeq ($(BUILD_PROFILE),debug)
PROFILE_CFLAGS = -g -O0
PROFILE_LDFLAGS = -fsanitize=address,undefined
else ifeq ($(BUILD_PROFILE),perf)
PROFILE_CFLAGS = -O3 -DNDEBUG
ifeq ($(FISICS_SANITIZED),1)
PROFILE_LDFLAGS = -fsanitize=address,undefined
else
PROFILE_LDFLAGS =
endif
else
$(error Unsupported BUILD_PROFILE '$(BUILD_PROFILE)' (expected debug or perf))
endif

CFLAGS  = $(BASE_CFLAGS) $(PROFILE_CFLAGS)

ifeq ($(strip $(VULKAN_RENDER_DEBUG)),1)
CFLAGS += -DVK_RENDERER_DEBUG=1
ifeq ($(strip $(VULKAN_RENDER_DEBUG_FRAMES)),1)
CFLAGS += -DVK_RENDERER_FRAME_DEBUG=1
endif
endif
LDFLAGS = $(ARCH_FLAGS) $(BASE_LDFLAGS) $(PROFILE_LDFLAGS)
